version: '3.8'

services:
  # Service principal de l'API
  api-livres:
    build: .
    container_name: api-livres-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_PATH=/app/data/database.sqlite
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/books"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - api-network

  # Service pour le monitoring (optionnel)
  # Vous pouvez décommenter pour ajouter Prometheus
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: api-livres-prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - api-network

  # Service de reverse proxy (optionnel)
  # nginx:
  #   image: nginx:alpine
  #   container_name: api-livres-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - api-livres
  #   networks:
  #     - api-network

networks:
  api-network:
    driver: bridge

volumes:
  api-data:
    driver: local
